language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config python-numpy libgeos-dev libgeos++-dev
install:
  - "pip install -r requirements.txt --allow-external basemap --allow-unverified basemap"
script: 
  - "python setup.py install"
  - "python test/daynighttesting.py"
